/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.dao.VeiculoDAO;
import java.sql.*;
import javax.swing.JOptionPane;
import model.bean.Veiculo;
/**
 *
 * @author livio
 */
public class telaCadastroV extends javax.swing.JFrame {
    /**
     * Creates new form telaCadastroV
     */
    public telaCadastroV() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtVeiculo.getModel();
        jtVeiculo.setRowSorter(new TableRowSorter(modelo));
        restaurarDadosCBX();
        readjtVeiculo();      
    }
    
    public void readjtVeiculo(){
        DefaultTableModel modelo = (DefaultTableModel) jtVeiculo.getModel();
        modelo.setNumRows(0);   
        VeiculoDAO vdao = new VeiculoDAO();
        
        for(Veiculo v: vdao.read()){
            modelo.addRow(new Object[]{
               v.getId(),
               v.getPlaca(),
               v.getCor(),
               v.getValor_dia(),
               v.getModelo(),
               v.getAno(),
               v.getKm(),
               v.getCombustivel(),
               v.getCodAgencia(),                     
            });
        }
    }
    
    Vector<Integer> idAgencia = new Vector<Integer>();
    public void restaurarDadosCBX(){
        
        try {
             VeiculoDAO objAgencia = new VeiculoDAO();
             ResultSet rs = objAgencia.listarAgencia();
             
             while (rs.next()){
                 idAgencia.addElement(rs.getInt(1));
                 cbxAgencia.addItem(rs.getString(1));
             }
             
        } catch (SQLException ex){
            JOptionPane.showMessageDialog(null, "Carregar cargo view: " + ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPainelDeDados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtCor = new javax.swing.JTextField();
        txtValorDia = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtKm = new javax.swing.JTextField();
        txtCombustivel = new javax.swing.JTextField();
        jBCadastrar = new javax.swing.JButton();
        txtAno = new javax.swing.JFormattedTextField();
        jBAtualizar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        jBPesquisar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cbxAgencia = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVeiculo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Placa");

        jLabel2.setText("Cor");

        jLabel3.setText("Valor da diária");

        jLabel4.setText("Km");

        jLabel5.setText("Ano");

        jLabel6.setText("Modelo");

        jLabel7.setText("Combustível");

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jBAtualizar.setText("Atualizar");
        jBAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtualizarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBPesquisar.setText("Buscar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jLabel8.setText("Agência");

        javax.swing.GroupLayout jPainelDeDadosLayout = new javax.swing.GroupLayout(jPainelDeDados);
        jPainelDeDados.setLayout(jPainelDeDadosLayout);
        jPainelDeDadosLayout.setHorizontalGroup(
            jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelDeDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPainelDeDadosLayout.createSequentialGroup()
                        .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCor)
                            .addComponent(txtValorDia, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAno)
                                .addComponent(txtKm, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                            .addComponent(jLabel4)))
                    .addGroup(jPainelDeDadosLayout.createSequentialGroup()
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(jPainelDeDadosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(190, 190, 190)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPainelDeDadosLayout.createSequentialGroup()
                        .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPainelDeDadosLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 48, Short.MAX_VALUE))
                            .addComponent(cbxAgencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPainelDeDadosLayout.createSequentialGroup()
                        .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPainelDeDadosLayout.createSequentialGroup()
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPainelDeDadosLayout.createSequentialGroup()
                                .addComponent(jBCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAtualizar)
                                .addGap(23, 23, 23)))
                        .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                            .addComponent(jBPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPainelDeDadosLayout.setVerticalGroup(
            jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPainelDeDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBPesquisar))
                .addGap(5, 5, 5)
                .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPainelDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBAtualizar)
                    .addComponent(jBExcluir))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jtVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Placa", "Cor", "Valor da Diária", "Modelo", "Ano", "Km", "Combustível", "Agência"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVeiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVeiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtVeiculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPainelDeDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPainelDeDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        // TODO add your handling code here:
        Veiculo v = new Veiculo();     
        VeiculoDAO dao = new VeiculoDAO();

        v.setPlaca(txtPlaca.getText());
        v.setModelo(txtModelo.getText());
        v.setCor(txtCor.getText());
        v.setAno(txtAno.getText());
        v.setValor_dia(Float.parseFloat(txtValorDia.getText()));
        v.setKm(Integer.parseInt(txtKm.getText()));
        v.setCombustivel(txtCombustivel.getText());
        
        int codAgencia;
        codAgencia = idAgencia.get(cbxAgencia.getSelectedIndex());
        v.setCodAgencia(codAgencia);
        
        dao.create(v);
        txtPlaca.setText("");
        txtAno.setText("");
        txtCombustivel.setText("");
        txtCor.setText("");
        txtKm.setText("");
        txtModelo.setText("");
        txtValorDia.setText("");
         readjtVeiculo();       
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jtVeiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVeiculoMouseClicked
        // TODO add your handling code here:
        
        if(jtVeiculo.getSelectedRow() != -1){
            txtPlaca.setText(jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),1).toString());
            txtCor.setText(jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),2).toString());
            txtValorDia.setText(jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),3).toString());
            txtModelo.setText(jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),4).toString());
            txtAno.setText(jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),5).toString());
            txtKm.setText(jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),6).toString());
            txtCombustivel.setText(jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),7).toString());
            jtVeiculo.getValueAt(cbxAgencia.getSelectedIndex(), 8);
            
            
        }
    }//GEN-LAST:event_jtVeiculoMouseClicked

    private void jBAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtualizarActionPerformed
        // TODO add your handling code here:
        
        Veiculo v = new Veiculo();
        VeiculoDAO dao = new VeiculoDAO();
        v.setPlaca(txtPlaca.getText());
        v.setModelo(txtModelo.getText());
        v.setCor(txtCor.getText());
        v.setAno(txtAno.getText());
        v.setValor_dia(Float.parseFloat(txtValorDia.getText()));
        v.setKm(Integer.parseInt(txtKm.getText()));
        v.setCombustivel(txtCombustivel.getText());
        v.setId((int)jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),0));
        
        int codAgencia;
        codAgencia = idAgencia.get(cbxAgencia.getSelectedIndex());
        v.setCodAgencia(codAgencia);
        
        dao.update(v);
        txtPlaca.setText("");
        txtAno.setText("");
        txtCombustivel.setText("");
        txtCor.setText("");
        txtKm.setText("");
        txtModelo.setText("");
        txtValorDia.setText("");
        
        readjtVeiculo();
    }//GEN-LAST:event_jBAtualizarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
        
        if (jtVeiculo.getSelectedRow() != -1){
            Veiculo v = new Veiculo();
        VeiculoDAO dao = new VeiculoDAO();
        
        v.setId((int)jtVeiculo.getValueAt(jtVeiculo.getSelectedRow(),0));
        
        dao.remove(v);
        txtPlaca.setText("");
        txtAno.setText("");
        txtCombustivel.setText("");
        txtCor.setText("");
        txtKm.setText("");
        txtModelo.setText("");
        txtValorDia.setText("");
        
        readjtVeiculo();
        } else{
            JOptionPane.showMessageDialog(null, "Selecione um veiculo para excluir");
        }
        
    }//GEN-LAST:event_jBExcluirActionPerformed
    
    public void buscjTBusca(String busc){    
        DefaultTableModel modelo = (DefaultTableModel) jtVeiculo.getModel();
        modelo.setNumRows(0);   
        VeiculoDAO vdao = new VeiculoDAO();
        
        for(Veiculo v: vdao.buscaB(busc)){
            modelo.addRow(new Object[]{
               v.getId(),
               v.getPlaca(),
               v.getCor(),
               v.getValor_dia(),
               v.getModelo(),
               v.getAno(),
               v.getKm(),
               v.getCombustivel(),       
            });
      } }
    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        // TODO add your handling code here:}
        buscjTBusca(txtPesquisa.getText());
    }//GEN-LAST:event_jBPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaCadastroV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaCadastroV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaCadastroV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaCadastroV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaCadastroV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxAgencia;
    private javax.swing.JButton jBAtualizar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPainelDeDados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtVeiculo;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JTextField txtCombustivel;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtKm;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtValorDia;
    // End of variables declaration//GEN-END:variables
}
