/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Reserva;
import model.dao.ReservaDAO;

/**
 *
 * @author livio
 */
public class telaReserva extends javax.swing.JFrame {

    /**
     * Creates new form telaReserva
     */
    public telaReserva() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jtReserva.getModel();
        jtReserva.setRowSorter(new TableRowSorter(modelo));
        readjtReserva();
    }
   
    public void readjtReserva(){
        DefaultTableModel modelo = (DefaultTableModel) jtReserva.getModel();
        modelo.setNumRows(0);   
        ReservaDAO rdao = new ReservaDAO();
        
        for(Reserva r: rdao.read()){
            modelo.addRow(new Object[]{
               r.getIdReserva(),
               r.getDataRetirada(),
               r.getDataEntrega(),
               r.getValor(),
               r.getCodAgencia(),
               r.getCodVeiculo(),
               r.getNomeCliente(),
               
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        veiculoDAO1 = new model.dao.VeiculoDAO();
        jPanel3 = new javax.swing.JPanel();
        txtdataentrg = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        txtDataretirada = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtReserva = new javax.swing.JTable();
        jBCadastrarC = new javax.swing.JButton();
        jBCadastrarV = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();
        JbAtualizar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        jBusca = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data de Retirada");

        jLabel3.setText("Data de Entrega");

        jLabel5.setText("Valor");

        jtReserva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Reserva", "Data de Retirada", "Data de entrega", "Cliente", "Agencia", "ID Veiculo", "Valor do Aluguel"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtReservaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtReserva);

        jBCadastrarC.setText("Cadastrar Cliente");
        jBCadastrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarCActionPerformed(evt);
            }
        });

        jBCadastrarV.setText("Cadastrar Veiculo");
        jBCadastrarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarVActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        JbAtualizar.setText("Atualizar");
        JbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAtualizarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        jBusca.setText("Buscar");
        jBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtdataentrg, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtBusca))
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBusca)
                                .addGap(133, 133, 133)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBCadastrarV)
                            .addComponent(jBCadastrarC, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataretirada, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbAtualizar)
                            .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataretirada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JbAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdataentrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBExcluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jBCadastrarC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCadastrarV)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCadastrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarCActionPerformed
        // TODO add your handling code here:
        new telaCadastroC().setVisible(true);
    }//GEN-LAST:event_jBCadastrarCActionPerformed

    private void jBCadastrarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarVActionPerformed
        // TODO add your handling code here:
        new telaCadastroV().setVisible(true);
    }//GEN-LAST:event_jBCadastrarVActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        // TODO add your handling code here:
        Reserva r = new Reserva();
        ReservaDAO dao = new ReservaDAO();
        
        r.setDataRetirada(txtDataretirada.getText());
        r.setDataEntrega(txtdataentrg.getText());
        r.setValor(Float.parseFloat(txtValor.getText()));
        
        dao.create(r);
        txtDataretirada.setText("");
        txtdataentrg.setText("");
        txtValor.setText("");
        readjtReserva();
       
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void JbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAtualizarActionPerformed
        // TODO add your handling code here:
        
        Reserva r = new Reserva();
        ReservaDAO dao = new ReservaDAO();
        
        r.setDataRetirada(txtDataretirada.getText());
        r.setDataEntrega(txtdataentrg.getText());
        r.setValor(Float.parseFloat(txtValor.getText()));   
         r.setIdReserva((int)jtReserva.getValueAt(jtReserva.getSelectedRow(), 0));
     
        dao.update(r);
        txtDataretirada.setText("");
        txtdataentrg.setText("");
        txtValor.setText("");
        readjtReserva();
        
    }//GEN-LAST:event_JbAtualizarActionPerformed

    private void jtReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtReservaMouseClicked
        // TODO add your handling code here:
        
        if(jtReserva.getSelectedRow() != -1){
            txtDataretirada.setText(jtReserva.getValueAt(jtReserva.getSelectedRow(),1).toString());
            txtdataentrg.setText(jtReserva.getValueAt(jtReserva.getSelectedRow(),2).toString());
            txtValor.setText(jtReserva.getValueAt(jtReserva.getSelectedRow(),3).toString());
           
            //problema ao retornar os valores nos campos no campo uf.
        }
    }//GEN-LAST:event_jtReservaMouseClicked

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        // TODO add your handling code here:
       
        if (jtReserva.getSelectedRow() != -1){
            Reserva r = new Reserva();
            ReservaDAO dao = new ReservaDAO();

            r.setIdReserva((int)jtReserva.getValueAt(jtReserva.getSelectedRow(), 0));
            dao.remove(r);

            txtDataretirada.setText("");
            txtdataentrg.setText("");
            txtValor.setText("");
            readjtReserva();
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir");
        }  
    }//GEN-LAST:event_jBExcluirActionPerformed

    public void buscjRBusca(String busc){    
        DefaultTableModel modelo = (DefaultTableModel) jtReserva.getModel();
        modelo.setNumRows(0);   
        ReservaDAO rdao = new ReservaDAO();
        
        for(Reserva r: rdao.buscaB(busc)){
            modelo.addRow(new Object[]{
               r.getDataRetirada(),
               r.getDataEntrega(),
            }); 
        }
    } 
    private void jBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscaActionPerformed
        // TODO add your handling code here:
        buscjRBusca(txtBusca.getText());
    }//GEN-LAST:event_jBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAtualizar;
    private javax.swing.JButton jBCadastrarC;
    private javax.swing.JButton jBCadastrarV;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JTable jtReserva;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtDataretirada;
    private javax.swing.JTextField txtValor;
    private javax.swing.JTextField txtdataentrg;
    private model.dao.VeiculoDAO veiculoDAO1;
    // End of variables declaration//GEN-END:variables

}
